// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package quiz

import (
	"context"
	"fmt"
	"liveclass/idl/kitex_gen/common"
)

type CreateQuestionReq struct {
	LessonId   int64    `thrift:"LessonId,1" frugal:"1,default,i64" json:"LessonId"`
	Userid     int64    `thrift:"Userid,2" frugal:"2,default,i64" json:"Userid"`
	Content    string   `thrift:"Content,3" frugal:"3,default,string" json:"Content"`
	OptionsNum int32    `thrift:"OptionsNum,4" frugal:"4,default,i32" json:"OptionsNum"`
	Options    []string `thrift:"Options,5" frugal:"5,default,list<string>" json:"Options"`
	Answer     string   `thrift:"Answer,6" frugal:"6,default,string" json:"Answer"`
	Duration   int32    `thrift:"duration,7" frugal:"7,default,i32" json:"duration"`
}

func NewCreateQuestionReq() *CreateQuestionReq {
	return &CreateQuestionReq{}
}

func (p *CreateQuestionReq) InitDefault() {
}

func (p *CreateQuestionReq) GetLessonId() (v int64) {
	return p.LessonId
}

func (p *CreateQuestionReq) GetUserid() (v int64) {
	return p.Userid
}

func (p *CreateQuestionReq) GetContent() (v string) {
	return p.Content
}

func (p *CreateQuestionReq) GetOptionsNum() (v int32) {
	return p.OptionsNum
}

func (p *CreateQuestionReq) GetOptions() (v []string) {
	return p.Options
}

func (p *CreateQuestionReq) GetAnswer() (v string) {
	return p.Answer
}

func (p *CreateQuestionReq) GetDuration() (v int32) {
	return p.Duration
}
func (p *CreateQuestionReq) SetLessonId(val int64) {
	p.LessonId = val
}
func (p *CreateQuestionReq) SetUserid(val int64) {
	p.Userid = val
}
func (p *CreateQuestionReq) SetContent(val string) {
	p.Content = val
}
func (p *CreateQuestionReq) SetOptionsNum(val int32) {
	p.OptionsNum = val
}
func (p *CreateQuestionReq) SetOptions(val []string) {
	p.Options = val
}
func (p *CreateQuestionReq) SetAnswer(val string) {
	p.Answer = val
}
func (p *CreateQuestionReq) SetDuration(val int32) {
	p.Duration = val
}

func (p *CreateQuestionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateQuestionReq(%+v)", *p)
}

var fieldIDToName_CreateQuestionReq = map[int16]string{
	1: "LessonId",
	2: "Userid",
	3: "Content",
	4: "OptionsNum",
	5: "Options",
	6: "Answer",
	7: "duration",
}

type CreateQuestionResp struct {
	Resp *common.Resp `thrift:"resp,1" frugal:"1,default,common.Resp" json:"resp"`
}

func NewCreateQuestionResp() *CreateQuestionResp {
	return &CreateQuestionResp{}
}

func (p *CreateQuestionResp) InitDefault() {
}

var CreateQuestionResp_Resp_DEFAULT *common.Resp

func (p *CreateQuestionResp) GetResp() (v *common.Resp) {
	if !p.IsSetResp() {
		return CreateQuestionResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *CreateQuestionResp) SetResp(val *common.Resp) {
	p.Resp = val
}

func (p *CreateQuestionResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *CreateQuestionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateQuestionResp(%+v)", *p)
}

var fieldIDToName_CreateQuestionResp = map[int16]string{
	1: "resp",
}

type TorFAnswerReq struct {
	QuestionId int64  `thrift:"Question_id,1" frugal:"1,default,i64" json:"Question_id"`
	Userid     int64  `thrift:"Userid,2" frugal:"2,default,i64" json:"Userid"`
	UserAnswer string `thrift:"UserAnswer,3" frugal:"3,default,string" json:"UserAnswer"`
}

func NewTorFAnswerReq() *TorFAnswerReq {
	return &TorFAnswerReq{}
}

func (p *TorFAnswerReq) InitDefault() {
}

func (p *TorFAnswerReq) GetQuestionId() (v int64) {
	return p.QuestionId
}

func (p *TorFAnswerReq) GetUserid() (v int64) {
	return p.Userid
}

func (p *TorFAnswerReq) GetUserAnswer() (v string) {
	return p.UserAnswer
}
func (p *TorFAnswerReq) SetQuestionId(val int64) {
	p.QuestionId = val
}
func (p *TorFAnswerReq) SetUserid(val int64) {
	p.Userid = val
}
func (p *TorFAnswerReq) SetUserAnswer(val string) {
	p.UserAnswer = val
}

func (p *TorFAnswerReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TorFAnswerReq(%+v)", *p)
}

var fieldIDToName_TorFAnswerReq = map[int16]string{
	1: "Question_id",
	2: "Userid",
	3: "UserAnswer",
}

type TorFAnswerResp struct {
	Resp *common.Resp `thrift:"resp,1" frugal:"1,default,common.Resp" json:"resp"`
}

func NewTorFAnswerResp() *TorFAnswerResp {
	return &TorFAnswerResp{}
}

func (p *TorFAnswerResp) InitDefault() {
}

var TorFAnswerResp_Resp_DEFAULT *common.Resp

func (p *TorFAnswerResp) GetResp() (v *common.Resp) {
	if !p.IsSetResp() {
		return TorFAnswerResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *TorFAnswerResp) SetResp(val *common.Resp) {
	p.Resp = val
}

func (p *TorFAnswerResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *TorFAnswerResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TorFAnswerResp(%+v)", *p)
}

var fieldIDToName_TorFAnswerResp = map[int16]string{
	1: "resp",
}

type DelQuestionReq struct {
	Userid     int64 `thrift:"Userid,1" frugal:"1,default,i64" json:"Userid"`
	QuestionId int64 `thrift:"Question_id,2" frugal:"2,default,i64" json:"Question_id"`
}

func NewDelQuestionReq() *DelQuestionReq {
	return &DelQuestionReq{}
}

func (p *DelQuestionReq) InitDefault() {
}

func (p *DelQuestionReq) GetUserid() (v int64) {
	return p.Userid
}

func (p *DelQuestionReq) GetQuestionId() (v int64) {
	return p.QuestionId
}
func (p *DelQuestionReq) SetUserid(val int64) {
	p.Userid = val
}
func (p *DelQuestionReq) SetQuestionId(val int64) {
	p.QuestionId = val
}

func (p *DelQuestionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelQuestionReq(%+v)", *p)
}

var fieldIDToName_DelQuestionReq = map[int16]string{
	1: "Userid",
	2: "Question_id",
}

type DelQuestionResp struct {
	Resp *common.Resp `thrift:"resp,1" frugal:"1,default,common.Resp" json:"resp"`
}

func NewDelQuestionResp() *DelQuestionResp {
	return &DelQuestionResp{}
}

func (p *DelQuestionResp) InitDefault() {
}

var DelQuestionResp_Resp_DEFAULT *common.Resp

func (p *DelQuestionResp) GetResp() (v *common.Resp) {
	if !p.IsSetResp() {
		return DelQuestionResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *DelQuestionResp) SetResp(val *common.Resp) {
	p.Resp = val
}

func (p *DelQuestionResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *DelQuestionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelQuestionResp(%+v)", *p)
}

var fieldIDToName_DelQuestionResp = map[int16]string{
	1: "resp",
}

type GetAllLessonQuizReq struct {
	Userid   int64 `thrift:"userid,1" frugal:"1,default,i64" json:"userid"`
	LessonId int64 `thrift:"lesson_id,2" frugal:"2,default,i64" json:"lesson_id"`
}

func NewGetAllLessonQuizReq() *GetAllLessonQuizReq {
	return &GetAllLessonQuizReq{}
}

func (p *GetAllLessonQuizReq) InitDefault() {
}

func (p *GetAllLessonQuizReq) GetUserid() (v int64) {
	return p.Userid
}

func (p *GetAllLessonQuizReq) GetLessonId() (v int64) {
	return p.LessonId
}
func (p *GetAllLessonQuizReq) SetUserid(val int64) {
	p.Userid = val
}
func (p *GetAllLessonQuizReq) SetLessonId(val int64) {
	p.LessonId = val
}

func (p *GetAllLessonQuizReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAllLessonQuizReq(%+v)", *p)
}

var fieldIDToName_GetAllLessonQuizReq = map[int16]string{
	1: "userid",
	2: "lesson_id",
}

type GetAllLessonQuizResp struct {
	Resp *common.Resp `thrift:"resp,1" frugal:"1,default,common.Resp" json:"resp"`
}

func NewGetAllLessonQuizResp() *GetAllLessonQuizResp {
	return &GetAllLessonQuizResp{}
}

func (p *GetAllLessonQuizResp) InitDefault() {
}

var GetAllLessonQuizResp_Resp_DEFAULT *common.Resp

func (p *GetAllLessonQuizResp) GetResp() (v *common.Resp) {
	if !p.IsSetResp() {
		return GetAllLessonQuizResp_Resp_DEFAULT
	}
	return p.Resp
}
func (p *GetAllLessonQuizResp) SetResp(val *common.Resp) {
	p.Resp = val
}

func (p *GetAllLessonQuizResp) IsSetResp() bool {
	return p.Resp != nil
}

func (p *GetAllLessonQuizResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAllLessonQuizResp(%+v)", *p)
}

var fieldIDToName_GetAllLessonQuizResp = map[int16]string{
	1: "resp",
}

type QuizService interface {
	CreateQuestion(ctx context.Context, req *CreateQuestionReq) (r *CreateQuestionResp, err error)

	TorFAnswer(ctx context.Context, req *TorFAnswerReq) (r *TorFAnswerResp, err error)

	DelQuestion(ctx context.Context, req *DelQuestionReq) (r *DelQuestionResp, err error)

	GetAllLessonQuiz(ctx context.Context, req *GetAllLessonQuizReq) (r *GetAllLessonQuizResp, err error)
}

type QuizServiceCreateQuestionArgs struct {
	Req *CreateQuestionReq `thrift:"req,1" frugal:"1,default,CreateQuestionReq" json:"req"`
}

func NewQuizServiceCreateQuestionArgs() *QuizServiceCreateQuestionArgs {
	return &QuizServiceCreateQuestionArgs{}
}

func (p *QuizServiceCreateQuestionArgs) InitDefault() {
}

var QuizServiceCreateQuestionArgs_Req_DEFAULT *CreateQuestionReq

func (p *QuizServiceCreateQuestionArgs) GetReq() (v *CreateQuestionReq) {
	if !p.IsSetReq() {
		return QuizServiceCreateQuestionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *QuizServiceCreateQuestionArgs) SetReq(val *CreateQuestionReq) {
	p.Req = val
}

func (p *QuizServiceCreateQuestionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuizServiceCreateQuestionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceCreateQuestionArgs(%+v)", *p)
}

var fieldIDToName_QuizServiceCreateQuestionArgs = map[int16]string{
	1: "req",
}

type QuizServiceCreateQuestionResult struct {
	Success *CreateQuestionResp `thrift:"success,0,optional" frugal:"0,optional,CreateQuestionResp" json:"success,omitempty"`
}

func NewQuizServiceCreateQuestionResult() *QuizServiceCreateQuestionResult {
	return &QuizServiceCreateQuestionResult{}
}

func (p *QuizServiceCreateQuestionResult) InitDefault() {
}

var QuizServiceCreateQuestionResult_Success_DEFAULT *CreateQuestionResp

func (p *QuizServiceCreateQuestionResult) GetSuccess() (v *CreateQuestionResp) {
	if !p.IsSetSuccess() {
		return QuizServiceCreateQuestionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *QuizServiceCreateQuestionResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateQuestionResp)
}

func (p *QuizServiceCreateQuestionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuizServiceCreateQuestionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceCreateQuestionResult(%+v)", *p)
}

var fieldIDToName_QuizServiceCreateQuestionResult = map[int16]string{
	0: "success",
}

type QuizServiceTorFAnswerArgs struct {
	Req *TorFAnswerReq `thrift:"req,1" frugal:"1,default,TorFAnswerReq" json:"req"`
}

func NewQuizServiceTorFAnswerArgs() *QuizServiceTorFAnswerArgs {
	return &QuizServiceTorFAnswerArgs{}
}

func (p *QuizServiceTorFAnswerArgs) InitDefault() {
}

var QuizServiceTorFAnswerArgs_Req_DEFAULT *TorFAnswerReq

func (p *QuizServiceTorFAnswerArgs) GetReq() (v *TorFAnswerReq) {
	if !p.IsSetReq() {
		return QuizServiceTorFAnswerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *QuizServiceTorFAnswerArgs) SetReq(val *TorFAnswerReq) {
	p.Req = val
}

func (p *QuizServiceTorFAnswerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuizServiceTorFAnswerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceTorFAnswerArgs(%+v)", *p)
}

var fieldIDToName_QuizServiceTorFAnswerArgs = map[int16]string{
	1: "req",
}

type QuizServiceTorFAnswerResult struct {
	Success *TorFAnswerResp `thrift:"success,0,optional" frugal:"0,optional,TorFAnswerResp" json:"success,omitempty"`
}

func NewQuizServiceTorFAnswerResult() *QuizServiceTorFAnswerResult {
	return &QuizServiceTorFAnswerResult{}
}

func (p *QuizServiceTorFAnswerResult) InitDefault() {
}

var QuizServiceTorFAnswerResult_Success_DEFAULT *TorFAnswerResp

func (p *QuizServiceTorFAnswerResult) GetSuccess() (v *TorFAnswerResp) {
	if !p.IsSetSuccess() {
		return QuizServiceTorFAnswerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *QuizServiceTorFAnswerResult) SetSuccess(x interface{}) {
	p.Success = x.(*TorFAnswerResp)
}

func (p *QuizServiceTorFAnswerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuizServiceTorFAnswerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceTorFAnswerResult(%+v)", *p)
}

var fieldIDToName_QuizServiceTorFAnswerResult = map[int16]string{
	0: "success",
}

type QuizServiceDelQuestionArgs struct {
	Req *DelQuestionReq `thrift:"req,1" frugal:"1,default,DelQuestionReq" json:"req"`
}

func NewQuizServiceDelQuestionArgs() *QuizServiceDelQuestionArgs {
	return &QuizServiceDelQuestionArgs{}
}

func (p *QuizServiceDelQuestionArgs) InitDefault() {
}

var QuizServiceDelQuestionArgs_Req_DEFAULT *DelQuestionReq

func (p *QuizServiceDelQuestionArgs) GetReq() (v *DelQuestionReq) {
	if !p.IsSetReq() {
		return QuizServiceDelQuestionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *QuizServiceDelQuestionArgs) SetReq(val *DelQuestionReq) {
	p.Req = val
}

func (p *QuizServiceDelQuestionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuizServiceDelQuestionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceDelQuestionArgs(%+v)", *p)
}

var fieldIDToName_QuizServiceDelQuestionArgs = map[int16]string{
	1: "req",
}

type QuizServiceDelQuestionResult struct {
	Success *DelQuestionResp `thrift:"success,0,optional" frugal:"0,optional,DelQuestionResp" json:"success,omitempty"`
}

func NewQuizServiceDelQuestionResult() *QuizServiceDelQuestionResult {
	return &QuizServiceDelQuestionResult{}
}

func (p *QuizServiceDelQuestionResult) InitDefault() {
}

var QuizServiceDelQuestionResult_Success_DEFAULT *DelQuestionResp

func (p *QuizServiceDelQuestionResult) GetSuccess() (v *DelQuestionResp) {
	if !p.IsSetSuccess() {
		return QuizServiceDelQuestionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *QuizServiceDelQuestionResult) SetSuccess(x interface{}) {
	p.Success = x.(*DelQuestionResp)
}

func (p *QuizServiceDelQuestionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuizServiceDelQuestionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceDelQuestionResult(%+v)", *p)
}

var fieldIDToName_QuizServiceDelQuestionResult = map[int16]string{
	0: "success",
}

type QuizServiceGetAllLessonQuizArgs struct {
	Req *GetAllLessonQuizReq `thrift:"req,1" frugal:"1,default,GetAllLessonQuizReq" json:"req"`
}

func NewQuizServiceGetAllLessonQuizArgs() *QuizServiceGetAllLessonQuizArgs {
	return &QuizServiceGetAllLessonQuizArgs{}
}

func (p *QuizServiceGetAllLessonQuizArgs) InitDefault() {
}

var QuizServiceGetAllLessonQuizArgs_Req_DEFAULT *GetAllLessonQuizReq

func (p *QuizServiceGetAllLessonQuizArgs) GetReq() (v *GetAllLessonQuizReq) {
	if !p.IsSetReq() {
		return QuizServiceGetAllLessonQuizArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *QuizServiceGetAllLessonQuizArgs) SetReq(val *GetAllLessonQuizReq) {
	p.Req = val
}

func (p *QuizServiceGetAllLessonQuizArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QuizServiceGetAllLessonQuizArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceGetAllLessonQuizArgs(%+v)", *p)
}

var fieldIDToName_QuizServiceGetAllLessonQuizArgs = map[int16]string{
	1: "req",
}

type QuizServiceGetAllLessonQuizResult struct {
	Success *GetAllLessonQuizResp `thrift:"success,0,optional" frugal:"0,optional,GetAllLessonQuizResp" json:"success,omitempty"`
}

func NewQuizServiceGetAllLessonQuizResult() *QuizServiceGetAllLessonQuizResult {
	return &QuizServiceGetAllLessonQuizResult{}
}

func (p *QuizServiceGetAllLessonQuizResult) InitDefault() {
}

var QuizServiceGetAllLessonQuizResult_Success_DEFAULT *GetAllLessonQuizResp

func (p *QuizServiceGetAllLessonQuizResult) GetSuccess() (v *GetAllLessonQuizResp) {
	if !p.IsSetSuccess() {
		return QuizServiceGetAllLessonQuizResult_Success_DEFAULT
	}
	return p.Success
}
func (p *QuizServiceGetAllLessonQuizResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAllLessonQuizResp)
}

func (p *QuizServiceGetAllLessonQuizResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QuizServiceGetAllLessonQuizResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizServiceGetAllLessonQuizResult(%+v)", *p)
}

var fieldIDToName_QuizServiceGetAllLessonQuizResult = map[int16]string{
	0: "success",
}
