// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package common

import (
	"fmt"
)

type Resp struct {
	Code int16  `thrift:"Code,1" frugal:"1,default,i16" json:"Code"`
	Msg  string `thrift:"Msg,2" frugal:"2,default,string" json:"Msg"`
	Data *Data  `thrift:"Data,3,optional" frugal:"3,optional,Data" json:"Data,omitempty"`
}

func NewResp() *Resp {
	return &Resp{}
}

func (p *Resp) InitDefault() {
}

func (p *Resp) GetCode() (v int16) {
	return p.Code
}

func (p *Resp) GetMsg() (v string) {
	return p.Msg
}

var Resp_Data_DEFAULT *Data

func (p *Resp) GetData() (v *Data) {
	if !p.IsSetData() {
		return Resp_Data_DEFAULT
	}
	return p.Data
}
func (p *Resp) SetCode(val int16) {
	p.Code = val
}
func (p *Resp) SetMsg(val string) {
	p.Msg = val
}
func (p *Resp) SetData(val *Data) {
	p.Data = val
}

func (p *Resp) IsSetData() bool {
	return p.Data != nil
}

func (p *Resp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Resp(%+v)", *p)
}

var fieldIDToName_Resp = map[int16]string{
	1: "Code",
	2: "Msg",
	3: "Data",
}

type User struct {
	UserID   int64  `thrift:"UserID,1" frugal:"1,default,i64" json:"UserID"`
	UserName string `thrift:"UserName,2" frugal:"2,default,string" json:"UserName"`
	Auth     string `thrift:"Auth,3" frugal:"3,default,string" json:"Auth"`
	Status   int8   `thrift:"Status,4" frugal:"4,default,i8" json:"Status"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetUserID() (v int64) {
	return p.UserID
}

func (p *User) GetUserName() (v string) {
	return p.UserName
}

func (p *User) GetAuth() (v string) {
	return p.Auth
}

func (p *User) GetStatus() (v int8) {
	return p.Status
}
func (p *User) SetUserID(val int64) {
	p.UserID = val
}
func (p *User) SetUserName(val string) {
	p.UserName = val
}
func (p *User) SetAuth(val string) {
	p.Auth = val
}
func (p *User) SetStatus(val int8) {
	p.Status = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "UserID",
	2: "UserName",
	3: "Auth",
	4: "Status",
}

type Lesson struct {
	LessonID    int64   `thrift:"LessonID,1" frugal:"1,default,i64" json:"LessonID"`
	Name        string  `thrift:"Name,2" frugal:"2,default,string" json:"Name"`
	TeacherName string  `thrift:"TeacherName,3" frugal:"3,default,string" json:"TeacherName"`
	Description string  `thrift:"Description,4" frugal:"4,default,string" json:"Description"`
	StudentID   []int64 `thrift:"StudentID,5" frugal:"5,default,list<i64>" json:"StudentID"`
	TeacherID   int64   `thrift:"TeacherID,6" frugal:"6,default,i64" json:"TeacherID"`
}

func NewLesson() *Lesson {
	return &Lesson{}
}

func (p *Lesson) InitDefault() {
}

func (p *Lesson) GetLessonID() (v int64) {
	return p.LessonID
}

func (p *Lesson) GetName() (v string) {
	return p.Name
}

func (p *Lesson) GetTeacherName() (v string) {
	return p.TeacherName
}

func (p *Lesson) GetDescription() (v string) {
	return p.Description
}

func (p *Lesson) GetStudentID() (v []int64) {
	return p.StudentID
}

func (p *Lesson) GetTeacherID() (v int64) {
	return p.TeacherID
}
func (p *Lesson) SetLessonID(val int64) {
	p.LessonID = val
}
func (p *Lesson) SetName(val string) {
	p.Name = val
}
func (p *Lesson) SetTeacherName(val string) {
	p.TeacherName = val
}
func (p *Lesson) SetDescription(val string) {
	p.Description = val
}
func (p *Lesson) SetStudentID(val []int64) {
	p.StudentID = val
}
func (p *Lesson) SetTeacherID(val int64) {
	p.TeacherID = val
}

func (p *Lesson) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Lesson(%+v)", *p)
}

var fieldIDToName_Lesson = map[int16]string{
	1: "LessonID",
	2: "Name",
	3: "TeacherName",
	4: "Description",
	5: "StudentID",
	6: "TeacherID",
}

type Quiz struct {
	QuizID     int64       `thrift:"QuizID,1" frugal:"1,default,i64" json:"QuizID"`
	LessonID   int64       `thrift:"LessonID,2" frugal:"2,default,i64" json:"LessonID"`
	Content    string      `thrift:"Content,3" frugal:"3,default,string" json:"Content"`
	OptionsNum int8        `thrift:"OptionsNum,4" frugal:"4,default,i8" json:"OptionsNum"`
	Options    string      `thrift:"Options,5" frugal:"5,default,string" json:"Options"`
	Answer     string      `thrift:"Answer,6" frugal:"6,default,string" json:"Answer"`
	TeacherID  int64       `thrift:"TeacherID,7" frugal:"7,default,i64" json:"TeacherID"`
	Stats      []*QuizStat `thrift:"Stats,8" frugal:"8,default,list<QuizStat>" json:"Stats"`
}

func NewQuiz() *Quiz {
	return &Quiz{}
}

func (p *Quiz) InitDefault() {
}

func (p *Quiz) GetQuizID() (v int64) {
	return p.QuizID
}

func (p *Quiz) GetLessonID() (v int64) {
	return p.LessonID
}

func (p *Quiz) GetContent() (v string) {
	return p.Content
}

func (p *Quiz) GetOptionsNum() (v int8) {
	return p.OptionsNum
}

func (p *Quiz) GetOptions() (v string) {
	return p.Options
}

func (p *Quiz) GetAnswer() (v string) {
	return p.Answer
}

func (p *Quiz) GetTeacherID() (v int64) {
	return p.TeacherID
}

func (p *Quiz) GetStats() (v []*QuizStat) {
	return p.Stats
}
func (p *Quiz) SetQuizID(val int64) {
	p.QuizID = val
}
func (p *Quiz) SetLessonID(val int64) {
	p.LessonID = val
}
func (p *Quiz) SetContent(val string) {
	p.Content = val
}
func (p *Quiz) SetOptionsNum(val int8) {
	p.OptionsNum = val
}
func (p *Quiz) SetOptions(val string) {
	p.Options = val
}
func (p *Quiz) SetAnswer(val string) {
	p.Answer = val
}
func (p *Quiz) SetTeacherID(val int64) {
	p.TeacherID = val
}
func (p *Quiz) SetStats(val []*QuizStat) {
	p.Stats = val
}

func (p *Quiz) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Quiz(%+v)", *p)
}

var fieldIDToName_Quiz = map[int16]string{
	1: "QuizID",
	2: "LessonID",
	3: "Content",
	4: "OptionsNum",
	5: "Options",
	6: "Answer",
	7: "TeacherID",
	8: "Stats",
}

type QuizStat struct {
	Option string `thrift:"option,1" frugal:"1,default,string" json:"option"`
	Count  int64  `thrift:"count,2" frugal:"2,default,i64" json:"count"`
}

func NewQuizStat() *QuizStat {
	return &QuizStat{}
}

func (p *QuizStat) InitDefault() {
}

func (p *QuizStat) GetOption() (v string) {
	return p.Option
}

func (p *QuizStat) GetCount() (v int64) {
	return p.Count
}
func (p *QuizStat) SetOption(val string) {
	p.Option = val
}
func (p *QuizStat) SetCount(val int64) {
	p.Count = val
}

func (p *QuizStat) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QuizStat(%+v)", *p)
}

var fieldIDToName_QuizStat = map[int16]string{
	1: "option",
	2: "count",
}

type Chat struct {
	Message string `thrift:"Message,1" frugal:"1,default,string" json:"Message"`
}

func NewChat() *Chat {
	return &Chat{}
}

func (p *Chat) InitDefault() {
}

func (p *Chat) GetMessage() (v string) {
	return p.Message
}
func (p *Chat) SetMessage(val string) {
	p.Message = val
}

func (p *Chat) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Chat(%+v)", *p)
}

var fieldIDToName_Chat = map[int16]string{
	1: "Message",
}

type Data struct {
	UserInfo   *User   `thrift:"userInfo,1,optional" frugal:"1,optional,User" json:"userInfo,omitempty"`
	LessonInfo *Lesson `thrift:"lessonInfo,2,optional" frugal:"2,optional,Lesson" json:"lessonInfo,omitempty"`
	QuizInfo   *Quiz   `thrift:"quizInfo,3,optional" frugal:"3,optional,Quiz" json:"quizInfo,omitempty"`
	ChatInfo   *Chat   `thrift:"chatInfo,4,optional" frugal:"4,optional,Chat" json:"chatInfo,omitempty"`
	Sdp        *string `thrift:"sdp,10,optional" frugal:"10,optional,string" json:"sdp,omitempty"`
	Filename   *string `thrift:"filename,11,optional" frugal:"11,optional,string" json:"filename,omitempty"`
	IdList     []int64 `thrift:"idList,12,optional" frugal:"12,optional,list<i64>" json:"idList,omitempty"`
	Text       *string `thrift:"text,13,optional" frugal:"13,optional,string" json:"text,omitempty"`
}

func NewData() *Data {
	return &Data{}
}

func (p *Data) InitDefault() {
}

var Data_UserInfo_DEFAULT *User

func (p *Data) GetUserInfo() (v *User) {
	if !p.IsSetUserInfo() {
		return Data_UserInfo_DEFAULT
	}
	return p.UserInfo
}

var Data_LessonInfo_DEFAULT *Lesson

func (p *Data) GetLessonInfo() (v *Lesson) {
	if !p.IsSetLessonInfo() {
		return Data_LessonInfo_DEFAULT
	}
	return p.LessonInfo
}

var Data_QuizInfo_DEFAULT *Quiz

func (p *Data) GetQuizInfo() (v *Quiz) {
	if !p.IsSetQuizInfo() {
		return Data_QuizInfo_DEFAULT
	}
	return p.QuizInfo
}

var Data_ChatInfo_DEFAULT *Chat

func (p *Data) GetChatInfo() (v *Chat) {
	if !p.IsSetChatInfo() {
		return Data_ChatInfo_DEFAULT
	}
	return p.ChatInfo
}

var Data_Sdp_DEFAULT string

func (p *Data) GetSdp() (v string) {
	if !p.IsSetSdp() {
		return Data_Sdp_DEFAULT
	}
	return *p.Sdp
}

var Data_Filename_DEFAULT string

func (p *Data) GetFilename() (v string) {
	if !p.IsSetFilename() {
		return Data_Filename_DEFAULT
	}
	return *p.Filename
}

var Data_IdList_DEFAULT []int64

func (p *Data) GetIdList() (v []int64) {
	if !p.IsSetIdList() {
		return Data_IdList_DEFAULT
	}
	return p.IdList
}

var Data_Text_DEFAULT string

func (p *Data) GetText() (v string) {
	if !p.IsSetText() {
		return Data_Text_DEFAULT
	}
	return *p.Text
}
func (p *Data) SetUserInfo(val *User) {
	p.UserInfo = val
}
func (p *Data) SetLessonInfo(val *Lesson) {
	p.LessonInfo = val
}
func (p *Data) SetQuizInfo(val *Quiz) {
	p.QuizInfo = val
}
func (p *Data) SetChatInfo(val *Chat) {
	p.ChatInfo = val
}
func (p *Data) SetSdp(val *string) {
	p.Sdp = val
}
func (p *Data) SetFilename(val *string) {
	p.Filename = val
}
func (p *Data) SetIdList(val []int64) {
	p.IdList = val
}
func (p *Data) SetText(val *string) {
	p.Text = val
}

func (p *Data) CountSetFieldsData() int {
	count := 0
	if p.IsSetUserInfo() {
		count++
	}
	if p.IsSetLessonInfo() {
		count++
	}
	if p.IsSetQuizInfo() {
		count++
	}
	if p.IsSetChatInfo() {
		count++
	}
	if p.IsSetSdp() {
		count++
	}
	if p.IsSetFilename() {
		count++
	}
	if p.IsSetIdList() {
		count++
	}
	if p.IsSetText() {
		count++
	}
	return count
}

func (p *Data) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *Data) IsSetLessonInfo() bool {
	return p.LessonInfo != nil
}

func (p *Data) IsSetQuizInfo() bool {
	return p.QuizInfo != nil
}

func (p *Data) IsSetChatInfo() bool {
	return p.ChatInfo != nil
}

func (p *Data) IsSetSdp() bool {
	return p.Sdp != nil
}

func (p *Data) IsSetFilename() bool {
	return p.Filename != nil
}

func (p *Data) IsSetIdList() bool {
	return p.IdList != nil
}

func (p *Data) IsSetText() bool {
	return p.Text != nil
}

func (p *Data) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Data(%+v)", *p)
}

var fieldIDToName_Data = map[int16]string{
	1:  "userInfo",
	2:  "lessonInfo",
	3:  "quizInfo",
	4:  "chatInfo",
	10: "sdp",
	11: "filename",
	12: "idList",
	13: "text",
}
