// Code generated by Kitex v0.12.3. DO NOT EDIT.

package liveservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	live "liveclass/idl/kitex_gen/live"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateLive(ctx context.Context, req *live.CreateLiveReq, callOptions ...callopt.Option) (r *live.CreateLiveResp, err error)
	CloseLive(ctx context.Context, req *live.CloseLiveReq, callOptions ...callopt.Option) (r *live.CloseLiveResp, err error)
	ChangeUserInLive(ctx context.Context, req *live.ChangeUserInLiveReq, callOptions ...callopt.Option) (r *live.ChangeUserInLiveResp, err error)
	SelectLessonInfo(ctx context.Context, req *live.SelectLessonInfoReq, callOptions ...callopt.Option) (r *live.SelectLessonInfoResp, err error)
	GetLessonInfo(ctx context.Context, req *live.GetLessonInfoReq, callOptions ...callopt.Option) (r *live.GetLessonInfoResp, err error)
	GetLessonInfoById(ctx context.Context, req *live.GetLessonInfoByIdReq, callOptions ...callopt.Option) (r *live.GetLessonInfoByIdResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLiveServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLiveServiceClient struct {
	*kClient
}

func (p *kLiveServiceClient) CreateLive(ctx context.Context, req *live.CreateLiveReq, callOptions ...callopt.Option) (r *live.CreateLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateLive(ctx, req)
}

func (p *kLiveServiceClient) CloseLive(ctx context.Context, req *live.CloseLiveReq, callOptions ...callopt.Option) (r *live.CloseLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseLive(ctx, req)
}

func (p *kLiveServiceClient) ChangeUserInLive(ctx context.Context, req *live.ChangeUserInLiveReq, callOptions ...callopt.Option) (r *live.ChangeUserInLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeUserInLive(ctx, req)
}

func (p *kLiveServiceClient) SelectLessonInfo(ctx context.Context, req *live.SelectLessonInfoReq, callOptions ...callopt.Option) (r *live.SelectLessonInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SelectLessonInfo(ctx, req)
}

func (p *kLiveServiceClient) GetLessonInfo(ctx context.Context, req *live.GetLessonInfoReq, callOptions ...callopt.Option) (r *live.GetLessonInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLessonInfo(ctx, req)
}

func (p *kLiveServiceClient) GetLessonInfoById(ctx context.Context, req *live.GetLessonInfoByIdReq, callOptions ...callopt.Option) (r *live.GetLessonInfoByIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLessonInfoById(ctx, req)
}
