// Code generated by Kitex v0.12.3. DO NOT EDIT.

package liveservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	live "liveclass/idl/kitex_gen/live"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateLive": kitex.NewMethodInfo(
		createLiveHandler,
		newLiveServiceCreateLiveArgs,
		newLiveServiceCreateLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CloseLive": kitex.NewMethodInfo(
		closeLiveHandler,
		newLiveServiceCloseLiveArgs,
		newLiveServiceCloseLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeUserInLive": kitex.NewMethodInfo(
		changeUserInLiveHandler,
		newLiveServiceChangeUserInLiveArgs,
		newLiveServiceChangeUserInLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SelectLessonInfo": kitex.NewMethodInfo(
		selectLessonInfoHandler,
		newLiveServiceSelectLessonInfoArgs,
		newLiveServiceSelectLessonInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLessonInfo": kitex.NewMethodInfo(
		getLessonInfoHandler,
		newLiveServiceGetLessonInfoArgs,
		newLiveServiceGetLessonInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLessonInfoById": kitex.NewMethodInfo(
		getLessonInfoByIdHandler,
		newLiveServiceGetLessonInfoByIdArgs,
		newLiveServiceGetLessonInfoByIdResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeUserToLesson": kitex.NewMethodInfo(
		changeUserToLessonHandler,
		newLiveServiceChangeUserToLessonArgs,
		newLiveServiceChangeUserToLessonResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"IsStudentInLesson": kitex.NewMethodInfo(
		isStudentInLessonHandler,
		newLiveServiceIsStudentInLessonArgs,
		newLiveServiceIsStudentInLessonResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RecordLesson": kitex.NewMethodInfo(
		recordLessonHandler,
		newLiveServiceRecordLessonArgs,
		newLiveServiceRecordLessonResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateSignIn": kitex.NewMethodInfo(
		createSignInHandler,
		newLiveServiceCreateSignInArgs,
		newLiveServiceCreateSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SignIn": kitex.NewMethodInfo(
		signInHandler,
		newLiveServiceSignInArgs,
		newLiveServiceSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SelectSignIn": kitex.NewMethodInfo(
		selectSignInHandler,
		newLiveServiceSelectSignInArgs,
		newLiveServiceSelectSignInResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DelSign": kitex.NewMethodInfo(
		delSignHandler,
		newLiveServiceDelSignArgs,
		newLiveServiceDelSignResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RollCallInRandom": kitex.NewMethodInfo(
		rollCallInRandomHandler,
		newLiveServiceRollCallInRandomArgs,
		newLiveServiceRollCallInRandomResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	liveServiceServiceInfo                = NewServiceInfo()
	liveServiceServiceInfoForClient       = NewServiceInfoForClient()
	liveServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return liveServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LiveService"
	handlerType := (*live.LiveService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "live",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func createLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceCreateLiveArgs)
	realResult := result.(*live.LiveServiceCreateLiveResult)
	success, err := handler.(live.LiveService).CreateLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceCreateLiveArgs() interface{} {
	return live.NewLiveServiceCreateLiveArgs()
}

func newLiveServiceCreateLiveResult() interface{} {
	return live.NewLiveServiceCreateLiveResult()
}

func closeLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceCloseLiveArgs)
	realResult := result.(*live.LiveServiceCloseLiveResult)
	success, err := handler.(live.LiveService).CloseLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceCloseLiveArgs() interface{} {
	return live.NewLiveServiceCloseLiveArgs()
}

func newLiveServiceCloseLiveResult() interface{} {
	return live.NewLiveServiceCloseLiveResult()
}

func changeUserInLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceChangeUserInLiveArgs)
	realResult := result.(*live.LiveServiceChangeUserInLiveResult)
	success, err := handler.(live.LiveService).ChangeUserInLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceChangeUserInLiveArgs() interface{} {
	return live.NewLiveServiceChangeUserInLiveArgs()
}

func newLiveServiceChangeUserInLiveResult() interface{} {
	return live.NewLiveServiceChangeUserInLiveResult()
}

func selectLessonInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceSelectLessonInfoArgs)
	realResult := result.(*live.LiveServiceSelectLessonInfoResult)
	success, err := handler.(live.LiveService).SelectLessonInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceSelectLessonInfoArgs() interface{} {
	return live.NewLiveServiceSelectLessonInfoArgs()
}

func newLiveServiceSelectLessonInfoResult() interface{} {
	return live.NewLiveServiceSelectLessonInfoResult()
}

func getLessonInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceGetLessonInfoArgs)
	realResult := result.(*live.LiveServiceGetLessonInfoResult)
	success, err := handler.(live.LiveService).GetLessonInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetLessonInfoArgs() interface{} {
	return live.NewLiveServiceGetLessonInfoArgs()
}

func newLiveServiceGetLessonInfoResult() interface{} {
	return live.NewLiveServiceGetLessonInfoResult()
}

func getLessonInfoByIdHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceGetLessonInfoByIdArgs)
	realResult := result.(*live.LiveServiceGetLessonInfoByIdResult)
	success, err := handler.(live.LiveService).GetLessonInfoById(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetLessonInfoByIdArgs() interface{} {
	return live.NewLiveServiceGetLessonInfoByIdArgs()
}

func newLiveServiceGetLessonInfoByIdResult() interface{} {
	return live.NewLiveServiceGetLessonInfoByIdResult()
}

func changeUserToLessonHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceChangeUserToLessonArgs)
	realResult := result.(*live.LiveServiceChangeUserToLessonResult)
	success, err := handler.(live.LiveService).ChangeUserToLesson(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceChangeUserToLessonArgs() interface{} {
	return live.NewLiveServiceChangeUserToLessonArgs()
}

func newLiveServiceChangeUserToLessonResult() interface{} {
	return live.NewLiveServiceChangeUserToLessonResult()
}

func isStudentInLessonHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceIsStudentInLessonArgs)
	realResult := result.(*live.LiveServiceIsStudentInLessonResult)
	success, err := handler.(live.LiveService).IsStudentInLesson(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceIsStudentInLessonArgs() interface{} {
	return live.NewLiveServiceIsStudentInLessonArgs()
}

func newLiveServiceIsStudentInLessonResult() interface{} {
	return live.NewLiveServiceIsStudentInLessonResult()
}

func recordLessonHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceRecordLessonArgs)
	realResult := result.(*live.LiveServiceRecordLessonResult)
	success, err := handler.(live.LiveService).RecordLesson(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceRecordLessonArgs() interface{} {
	return live.NewLiveServiceRecordLessonArgs()
}

func newLiveServiceRecordLessonResult() interface{} {
	return live.NewLiveServiceRecordLessonResult()
}

func createSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceCreateSignInArgs)
	realResult := result.(*live.LiveServiceCreateSignInResult)
	success, err := handler.(live.LiveService).CreateSignIn(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceCreateSignInArgs() interface{} {
	return live.NewLiveServiceCreateSignInArgs()
}

func newLiveServiceCreateSignInResult() interface{} {
	return live.NewLiveServiceCreateSignInResult()
}

func signInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceSignInArgs)
	realResult := result.(*live.LiveServiceSignInResult)
	success, err := handler.(live.LiveService).SignIn(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceSignInArgs() interface{} {
	return live.NewLiveServiceSignInArgs()
}

func newLiveServiceSignInResult() interface{} {
	return live.NewLiveServiceSignInResult()
}

func selectSignInHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceSelectSignInArgs)
	realResult := result.(*live.LiveServiceSelectSignInResult)
	success, err := handler.(live.LiveService).SelectSignIn(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceSelectSignInArgs() interface{} {
	return live.NewLiveServiceSelectSignInArgs()
}

func newLiveServiceSelectSignInResult() interface{} {
	return live.NewLiveServiceSelectSignInResult()
}

func delSignHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceDelSignArgs)
	realResult := result.(*live.LiveServiceDelSignResult)
	success, err := handler.(live.LiveService).DelSign(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceDelSignArgs() interface{} {
	return live.NewLiveServiceDelSignArgs()
}

func newLiveServiceDelSignResult() interface{} {
	return live.NewLiveServiceDelSignResult()
}

func rollCallInRandomHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceRollCallInRandomArgs)
	realResult := result.(*live.LiveServiceRollCallInRandomResult)
	success, err := handler.(live.LiveService).RollCallInRandom(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceRollCallInRandomArgs() interface{} {
	return live.NewLiveServiceRollCallInRandomArgs()
}

func newLiveServiceRollCallInRandomResult() interface{} {
	return live.NewLiveServiceRollCallInRandomResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateLive(ctx context.Context, req *live.CreateLiveReq) (r *live.CreateLiveResp, err error) {
	var _args live.LiveServiceCreateLiveArgs
	_args.Req = req
	var _result live.LiveServiceCreateLiveResult
	if err = p.c.Call(ctx, "CreateLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CloseLive(ctx context.Context, req *live.CloseLiveReq) (r *live.CloseLiveResp, err error) {
	var _args live.LiveServiceCloseLiveArgs
	_args.Req = req
	var _result live.LiveServiceCloseLiveResult
	if err = p.c.Call(ctx, "CloseLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeUserInLive(ctx context.Context, req *live.ChangeUserInLiveReq) (r *live.ChangeUserInLiveResp, err error) {
	var _args live.LiveServiceChangeUserInLiveArgs
	_args.Req = req
	var _result live.LiveServiceChangeUserInLiveResult
	if err = p.c.Call(ctx, "ChangeUserInLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SelectLessonInfo(ctx context.Context, req *live.SelectLessonInfoReq) (r *live.SelectLessonInfoResp, err error) {
	var _args live.LiveServiceSelectLessonInfoArgs
	_args.Req = req
	var _result live.LiveServiceSelectLessonInfoResult
	if err = p.c.Call(ctx, "SelectLessonInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLessonInfo(ctx context.Context, req *live.GetLessonInfoReq) (r *live.GetLessonInfoResp, err error) {
	var _args live.LiveServiceGetLessonInfoArgs
	_args.Req = req
	var _result live.LiveServiceGetLessonInfoResult
	if err = p.c.Call(ctx, "GetLessonInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLessonInfoById(ctx context.Context, req *live.GetLessonInfoByIdReq) (r *live.GetLessonInfoByIdResp, err error) {
	var _args live.LiveServiceGetLessonInfoByIdArgs
	_args.Req = req
	var _result live.LiveServiceGetLessonInfoByIdResult
	if err = p.c.Call(ctx, "GetLessonInfoById", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeUserToLesson(ctx context.Context, req *live.ChangeUserToLessonReq) (r *live.ChangeUserToLessonResp, err error) {
	var _args live.LiveServiceChangeUserToLessonArgs
	_args.Req = req
	var _result live.LiveServiceChangeUserToLessonResult
	if err = p.c.Call(ctx, "ChangeUserToLesson", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) IsStudentInLesson(ctx context.Context, req *live.IsStudentInLessonReq) (r *live.IsStudentInLessonResp, err error) {
	var _args live.LiveServiceIsStudentInLessonArgs
	_args.Req = req
	var _result live.LiveServiceIsStudentInLessonResult
	if err = p.c.Call(ctx, "IsStudentInLesson", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RecordLesson(ctx context.Context, req *live.RecordLessonReq) (r *live.RecordLessonResp, err error) {
	var _args live.LiveServiceRecordLessonArgs
	_args.Req = req
	var _result live.LiveServiceRecordLessonResult
	if err = p.c.Call(ctx, "RecordLesson", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateSignIn(ctx context.Context, req *live.CreateSignInReq) (r *live.CreateSignInResp, err error) {
	var _args live.LiveServiceCreateSignInArgs
	_args.Req = req
	var _result live.LiveServiceCreateSignInResult
	if err = p.c.Call(ctx, "CreateSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SignIn(ctx context.Context, req *live.SignInReq) (r *live.SignInResp, err error) {
	var _args live.LiveServiceSignInArgs
	_args.Req = req
	var _result live.LiveServiceSignInResult
	if err = p.c.Call(ctx, "SignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SelectSignIn(ctx context.Context, req *live.SelectSignInReq) (r *live.SelectSignInResp, err error) {
	var _args live.LiveServiceSelectSignInArgs
	_args.Req = req
	var _result live.LiveServiceSelectSignInResult
	if err = p.c.Call(ctx, "SelectSignIn", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelSign(ctx context.Context, req *live.DelSignInReq) (r *live.DelSignInResp, err error) {
	var _args live.LiveServiceDelSignArgs
	_args.Req = req
	var _result live.LiveServiceDelSignResult
	if err = p.c.Call(ctx, "DelSign", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RollCallInRandom(ctx context.Context, req *live.RollCallInRandomReq) (r *live.RollCallInRandomResp, err error) {
	var _args live.LiveServiceRollCallInRandomArgs
	_args.Req = req
	var _result live.LiveServiceRollCallInRandomResult
	if err = p.c.Call(ctx, "RollCallInRandom", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
