// Code generated by Kitex v0.16.1. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	chat "liveclass/idl/kitex_gen/chat"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LiveChat": kitex.NewMethodInfo(
		liveChatHandler,
		newChatServiceLiveChatArgs,
		newChatServiceLiveChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetHistory": kitex.NewMethodInfo(
		getHistoryHandler,
		newChatServiceGetHistoryArgs,
		newChatServiceGetHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DelHistory": kitex.NewMethodInfo(
		delHistoryHandler,
		newChatServiceDelHistoryArgs,
		newChatServiceDelHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*chat.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "chat",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func liveChatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceLiveChatArgs)
	realResult := result.(*chat.ChatServiceLiveChatResult)
	success, err := handler.(chat.ChatService).LiveChat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceLiveChatArgs() interface{} {
	return chat.NewChatServiceLiveChatArgs()
}

func newChatServiceLiveChatResult() interface{} {
	return chat.NewChatServiceLiveChatResult()
}

func getHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceGetHistoryArgs)
	realResult := result.(*chat.ChatServiceGetHistoryResult)
	success, err := handler.(chat.ChatService).GetHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceGetHistoryArgs() interface{} {
	return chat.NewChatServiceGetHistoryArgs()
}

func newChatServiceGetHistoryResult() interface{} {
	return chat.NewChatServiceGetHistoryResult()
}

func delHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*chat.ChatServiceDelHistoryArgs)
	realResult := result.(*chat.ChatServiceDelHistoryResult)
	success, err := handler.(chat.ChatService).DelHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceDelHistoryArgs() interface{} {
	return chat.NewChatServiceDelHistoryArgs()
}

func newChatServiceDelHistoryResult() interface{} {
	return chat.NewChatServiceDelHistoryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LiveChat(ctx context.Context, req *chat.LiveChatReq) (r *chat.LiveChatResp, err error) {
	var _args chat.ChatServiceLiveChatArgs
	_args.Req = req
	var _result chat.ChatServiceLiveChatResult
	if err = p.c.Call(ctx, "LiveChat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetHistory(ctx context.Context, req *chat.GetHistoryReq) (r *chat.GetHistoryResp, err error) {
	var _args chat.ChatServiceGetHistoryArgs
	_args.Req = req
	var _result chat.ChatServiceGetHistoryResult
	if err = p.c.Call(ctx, "GetHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelHistory(ctx context.Context, req *chat.DelHistoryReq) (r *chat.DelHistoryResp, err error) {
	var _args chat.ChatServiceDelHistoryArgs
	_args.Req = req
	var _result chat.ChatServiceDelHistoryResult
	if err = p.c.Call(ctx, "DelHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
