// Code generated by Kitex v0.12.3. DO NOT EDIT.

package quizservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	quiz "liveclass/idl/kitex_gen/quiz"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateQuestion": kitex.NewMethodInfo(
		createQuestionHandler,
		newQuizServiceCreateQuestionArgs,
		newQuizServiceCreateQuestionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TorFAnswer": kitex.NewMethodInfo(
		torFAnswerHandler,
		newQuizServiceTorFAnswerArgs,
		newQuizServiceTorFAnswerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	quizServiceServiceInfo                = NewServiceInfo()
	quizServiceServiceInfoForClient       = NewServiceInfoForClient()
	quizServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return quizServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "QuizService"
	handlerType := (*quiz.QuizService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "quiz",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.3",
		Extra:           extra,
	}
	return svcInfo
}

func createQuestionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*quiz.QuizServiceCreateQuestionArgs)
	realResult := result.(*quiz.QuizServiceCreateQuestionResult)
	success, err := handler.(quiz.QuizService).CreateQuestion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQuizServiceCreateQuestionArgs() interface{} {
	return quiz.NewQuizServiceCreateQuestionArgs()
}

func newQuizServiceCreateQuestionResult() interface{} {
	return quiz.NewQuizServiceCreateQuestionResult()
}

func torFAnswerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*quiz.QuizServiceTorFAnswerArgs)
	realResult := result.(*quiz.QuizServiceTorFAnswerResult)
	success, err := handler.(quiz.QuizService).TorFAnswer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQuizServiceTorFAnswerArgs() interface{} {
	return quiz.NewQuizServiceTorFAnswerArgs()
}

func newQuizServiceTorFAnswerResult() interface{} {
	return quiz.NewQuizServiceTorFAnswerResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateQuestion(ctx context.Context, req *quiz.CreateQuestionReq) (r *quiz.CreateQuestionResp, err error) {
	var _args quiz.QuizServiceCreateQuestionArgs
	_args.Req = req
	var _result quiz.QuizServiceCreateQuestionResult
	if err = p.c.Call(ctx, "CreateQuestion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TorFAnswer(ctx context.Context, req *quiz.TorFAnswerReq) (r *quiz.TorFAnswerResp, err error) {
	var _args quiz.QuizServiceTorFAnswerArgs
	_args.Req = req
	var _result quiz.QuizServiceTorFAnswerResult
	if err = p.c.Call(ctx, "TorFAnswer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
